[package]
name = "jetgpio-sys"
version = "0.1.0"
edition = "2021"
links = "jetgpio"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = "0.68.1"
cc = "1.0"
